### ISSUE TITLE
Node Version support

### ISSUE THREAD

**Issue by BenDiuguid** [UltimateSoftware/ng6-cli#34]
I think we should support Node LTS 4.0+

So this could allow for refactoring to make the code more maintainable/clean. 😃

We also recommend that people use node 6+ in the readme.

Thoughts?

**Comment by johnrjj** [comment]
Yeah, I'd be for LTS 4.x until April (4.x LTS support ends 2017-04-01, then moves into maintenance mode). 

However, I think there's a good argument for being 6.x+. The primary use case on the ng6-cli is new projects, specifically Angular 1.5+ projects, in order to support component architecture. I don't see existing legacy Angular 1.x projects buying into ng6-cli, for that reason, I don't think we would need to worry about supporting 4.x.  I don't think it would be crazy to require Node 6.x.

**Comment by BenDiuguid** [comment]
Yeah I agree, I just want to write `const` and `let` and use template strings haha, I keep unintentionally doing it 😆

**Comment by johnrjj** [comment]
Have we considered just using babel/webpack and giving a precompiled CLI instead?

**Comment by BenDiuguid** [comment]
@asleepinglion didn't want to, idr why but I'm fine with that

**Comment by asleepinglion** [comment]
Hehe, we can certainly revaluate my previous position, but the reasoning to avoid babel was due to how ng6 is meant to be extended and the simplicity of being able to just have things npm linked locally and re-execute the commands without a need to watch+compile. Maybe we can streamline that process and make it easy to do with npm scripts and alleviate that complexity. 

@BenDiuguid To the original question, how specifically can we refactor the code to improve things? Do other CLIs require Node 6+? If not, are they using babel to achieve this?

**Comment by johnrjj** [comment]
FWIW, the Angular 2 CLI requires Node 4

**Comment by BenDiuguid** [comment]
webpack uses >= 4.3 and create-react-app also uses >= 4

https://kangax.github.io/compat-table/es6/#node4 still lets us use a good amount of code, and then when we (eventually?) drop support for node 4 and move to node 6, migrating/upgrading will be easier.

**Comment by BenDiuguid** [comment]
Seems like moving forward we will be supporting Node 6+?
